version: '3'
networks:
  internal:
    driver: bridge
services:
  influxdb:
    hostname: influxdb
    container_name: influxdb
    image: influxdb:1.8
    networks:
      - internal
    volumes:
      - /path/to/docker-influxdb/config-folder:/var/lib/influxdb
    restart: unless-stopped
  varken:
    hostname: varken
    container_name: varken
    image: boerderij/varken
    networks:
      - internal
    volumes:
      - /path/to/docker-varken/config-folder:/config
    environment:
      - TZ=America/Chicago
      - VRKN_GLOBAL_SONARR_SERVER_IDS=1,2
      - VRKN_GLOBAL_RADARR_SERVER_IDS=1,2
      - VRKN_GLOBAL_LIDARR_SERVER_IDS=false
      - VRKN_GLOBAL_TAUTULLI_SERVER_IDS=1
      - VRKN_GLOBAL_OMBI_SERVER_IDS=1
      - VRKN_GLOBAL_SICKCHILL_SERVER_IDS=false
      - VRKN_GLOBAL_UNIFI_SERVER_IDS=false
      - VRKN_GLOBAL_MAXMIND_LICENSE_KEY=xxxxxxxxxxxxxxxx
      - VRKN_INFLUXDB_URL=influxdb.domain.tld
      - VRKN_INFLUXDB_PORT=8086
      - VRKN_INFLUXDB_SSL=false
      - VRKN_INFLUXDB_VERIFY_SSL=false
      - VRKN_INFLUXDB_USERNAME=root
      - VRKN_INFLUXDB_PASSWORD=root
      - VRKN_TAUTULLI_1_URL=tautulli.domain.tld:8181
      - VRKN_TAUTULLI_1_FALLBACK_IP=1.1.1.1
      - VRKN_TAUTULLI_1_APIKEY=xxxxxxxxxxxxxxxx
      - VRKN_TAUTULLI_1_SSL=false
      - VRKN_TAUTULLI_1_VERIFY_SSL=false
      - VRKN_TAUTULLI_1_GET_ACTIVITY=true
      - VRKN_TAUTULLI_1_GET_ACTIVITY_RUN_SECONDS=30
      - VRKN_TAUTULLI_1_GET_STATS=true
      - VRKN_TAUTULLI_1_GET_STATS_RUN_SECONDS=3600
      - VRKN_SONARR_1_URL=sonarr1.domain.tld:8989
      - VRKN_SONARR_1_APIKEY=xxxxxxxxxxxxxxxx
      - VRKN_SONARR_1_SSL=false
      - VRKN_SONARR_1_VERIFY_SSL=false
      - VRKN_SONARR_1_MISSING_DAYS=7
      - VRKN_SONARR_1_MISSING_DAYS_RUN_SECONDS=300
      - VRKN_SONARR_1_FUTURE_DAYS=1
      - VRKN_SONARR_1_FUTURE_DAYS_RUN_SECONDS=300
      - VRKN_SONARR_1_QUEUE=true
      - VRKN_SONARR_1_QUEUE_RUN_SECONDS=300
      - VRKN_SONARR_2_URL=sonarr2.domain.tld:8989
      - VRKN_SONARR_2_APIKEY=yyyyyyyyyyyyyyyy
      - VRKN_SONARR_2_SSL=false
      - VRKN_SONARR_2_VERIFY_SSL=false
      - VRKN_SONARR_2_MISSING_DAYS=7
      - VRKN_SONARR_2_MISSING_DAYS_RUN_SECONDS=300
      - VRKN_SONARR_2_FUTURE_DAYS=1
      - VRKN_SONARR_2_FUTURE_DAYS_RUN_SECONDS=300
      - VRKN_SONARR_2_QUEUE=true
      - VRKN_SONARR_2_QUEUE_RUN_SECONDS=300
      - VRKN_RADARR_1_URL=radarr1.domain.tld
      - VRKN_RADARR_1_APIKEY=xxxxxxxxxxxxxxxx
      - VRKN_RADARR_1_SSL=false
      - VRKN_RADARR_1_VERIFY_SSL=false
      - VRKN_RADARR_1_QUEUE=true
      - VRKN_RADARR_1_QUEUE_RUN_SECONDS=300
      - VRKN_RADARR_1_GET_MISSING=true
      - VRKN_RADARR_1_GET_MISSING_RUN_SECONDS=300
      - VRKN_RADARR_2_URL=radarr2.domain.tld
      - VRKN_RADARR_2_APIKEY=yyyyyyyyyyyyyyyy
      - VRKN_RADARR_2_SSL=false
      - VRKN_RADARR_2_VERIFY_SSL=false
      - VRKN_RADARR_2_QUEUE=true
      - VRKN_RADARR_2_QUEUE_RUN_SECONDS=300
      - VRKN_RADARR_2_GET_MISSING=true
      - VRKN_RADARR_2_GET_MISSING_RUN_SECONDS=300
      - VRKN_LIDARR_1_URL=lidarr1.domain.tld:8686
      - VRKN_LIDARR_1_APIKEY=xxxxxxxxxxxxxxxx
      - VRKN_LIDARR_1_SSL=false
      - VRKN_LIDARR_1_VERIFY_SSL=false
      - VRKN_LIDARR_1_MISSING_DAYS=30
      - VRKN_LIDARR_1_MISSING_DAYS_RUN_SECONDS=300
      - VRKN_LIDARR_1_FUTURE_DAYS=30
      - VRKN_LIDARR_1_FUTURE_DAYS_RUN_SECONDS=300
      - VRKN_LIDARR_1_QUEUE=true
      - VRKN_LIDARR_1_QUEUE_RUN_SECONDS=300
      - VRKN_OMBI_1_URL=ombi.domain.tld
      - VRKN_OMBI_1_APIKEY=xxxxxxxxxxxxxxxx
      - VRKN_OMBI_1_SSL=false
      - VRKN_OMBI_1_VERIFY_SSL=false
      - VRKN_OMBI_1_GET_REQUEST_TYPE_COUNTS=true
      - VRKN_OMBI_1_REQUEST_TYPE_RUN_SECONDS=300
      - VRKN_OMBI_1_GET_REQUEST_TOTAL_COUNTS=true
      - VRKN_OMBI_1_REQUEST_TOTAL_RUN_SECONDS=300
      - VRKN_OMBI_1_GET_ISSUE_STATUS_COUNTS=true
      - VRKN_OMBI_1_ISSUE_STATUS_RUN_SECONDS=300
      - VRKN_OVERSEERR_1_URL=ombi.domain.tld
      - VRKN_OVERSEERR_1_APIKEY=xxxxxxxxxxxxxxxx
      - VRKN_OVERSEERR_1_SSL=false
      - VRKN_OVERSEERR_1_VERIFY_SSL=false
      - VRKN_OVERSEERR_1_GET_REQUEST_TOTAL_COUNTS=true
      - VRKN_OVERSEERR_1_REQUEST_TOTAL_RUN_SECONDSS=30
      - VRKN_OVERSEERR_1_GET_LATEST_REQUESTS_TO_FETCH=10
      - VRKN_OVERSEERR_1_NUM_LATEST_REQUESTS_SECONDS=300
      - VRKN_SICKCHILL_1_URL=sickchill.domain.tld:8081
      - VRKN_SICKCHILL_1_APIKEY=xxxxxxxxxxxxxxxx
      - VRKN_SICKCHILL_1_SSL=false
      - VRKN_SICKCHILL_1_VERIFY_SSL=false
      - VRKN_SICKCHILL_1_GET_MISSING=true
      - VRKN_SICKCHILL_1_GET_MISSING_RUN_SECONDS=300
    depends_on:
      - influxdb
    restart: unless-stopped
  grafana:
    hostname: grafana
    container_name: grafana
    image: grafana/grafana
    networks:
      - internal
    ports:
      - 3000:3000
    volumes:
      - /path/to/docker-grafana/config-folder:/config
    environment:
      - GF_PATHS_DATA=/config/data
      - GF_PATHS_LOGS=/config/logs
      - GF_PATHS_PLUGINS=/config/plugins
      - GF_INSTALL_PLUGINS=grafana-piechart-panel,grafana-worldmap-panel
    depends_on:
      - influxdb
      - varken
    restart: unless-stopped
